Communicate test case item responsible for failure
redhat-partner-solutions/vse-sync-pp pull request #15
Opened 2023-06-02 16:10 UTC by spenced

```
======================================================================
FAIL: test_result:6
5, {'requirements': 'G.8272/PRTC-A', 'parameters': {'time-error-limit/%': 100,  (tests.vse_sync_pp.analyzers.test_ts2phc.TestTimeErrorAnalyzer.test_result:6
5, {'requirements': 'G.8272/PRTC-A', 'parameters': {'time-error-limit/%': 100, )
Test vse_sync_pp.analyzers.ts2phc.TimeErrorAnalyzer analyzer test result and analysis
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dspence/vse-sync-pp.git/tests/vse_sync_pp/analyzers/test_analyzer.py", line 187, in method
    self.assertEqual(analyzer.result, result, msg=msg)
AssertionError: False != True : (item 5 in `expect`)
```

2023-06-03 06:30 UTC, jnunyez commented
LGTM
Something may help is to filter a selected set of unit tests to run (e.g., run only ppsdpll unit tests).

2023-06-03 06:35 UTC, jnunyez approved these changes

2023-06-05 10:35 UTC, crwr45 requested changes
Basic approach looks good. Is the plan to apply the same pattern to the Parser tests once agreed here?

2023-06-05 10:35 UTC, crwr45 commented on tests/vse_sync_pp/analyzers/test_analyzer.py
> +            msg = f'(item {idx} in `expect`)'
I suggest adding the `fqname` to `msg`. It's already available in the scope and puts all the important information in a single message:

```suggestion
msg = f'(item {idx} in `expect` of {fqname})'
```

2023-09-06 07:25 UTC, spenced commented
Abandoning. (People aren't suffering because this hasn't been merged yet.)

2023-09-06 07:25 UTC, closed without merging