[DRAFT]: TTINTEL-291
redhat-partner-solutions/vse-sync-pp pull request #21
Opened 2023-06-22 17:31 UTC by jnunyez

2023-06-23 15:47 UTC, spenced requested changes

2023-06-23 15:47 UTC, spenced commented on src/vse_sync_pp/analyzers/phc2sys.py
> +"""Analyze ts2phc log messages"""
```suggestion
"""Analyze phc2sys log messages"""
```

2023-06-23 15:47 UTC, spenced commented on src/vse_sync_pp/parsers/phc2sys.py
> +"""Parse ts2phc log messages"""
```suggestion
"""Parse phc2sys log messages"""
```

2023-06-23 15:47 UTC, spenced commented on src/vse_sync_pp/parsers/phc2sys.py
> +    """Parse time error from a ts2phc log message"""
```suggestion
    """Parse time error from a phc2sys log message"""
```

2023-06-23 15:47 UTC, spenced commented on src/vse_sync_pp/requirements.py
> +    'workload/RAN': {
Where did the name come from?

2023-06-23 15:47 UTC, spenced commented on src/vse_sync_pp/requirements.py
> +        'time-error-in-locked-mode/ns': 100,
Where did the value come from?

2023-06-23 15:47 UTC, spenced commented on tests/vse_sync_pp/analyzers/test_phc2sys.py
> +"""Test cases for vse_sync_pp.analyzers.ts2phc"""
```suggestion
"""Test cases for vse_sync_pp.analyzers.phc2sys"""
```

2023-06-23 15:47 UTC, spenced commented on tests/vse_sync_pp/analyzers/test_phc2sys.py
> +    """Test cases for vse_sync_pp.analyzers.ts2phc.TimeErrorAnalyzer"""
```suggestion
    """Test cases for vse_sync_pp.analyzers.phc2sys.TimeErrorAnalyzer"""
```

2023-06-23 15:47 UTC, spenced commented on tests/vse_sync_pp/parsers/test_phc2sys.py
> +"""Test cases for vse_sync_pp.parsers.ts2phc"""
```suggestion
"""Test cases for vse_sync_pp.parsers.phc2sys"""
```

2023-06-23 15:47 UTC, spenced commented on tests/vse_sync_pp/parsers/test_phc2sys.py
> +    """Test cases for vse_sync_pp.parsers.ts2phc.TimeErrorParser"""
```suggestion
    """Test cases for vse_sync_pp.parsers.phc2sys.TimeErrorParser"""
```

2023-06-27 09:54 UTC, nocturnalastro commented on tests/vse_sync_pp/parsers/test_phc2sys.py
> +            'CLOCK_REALTIME phc offset          4 s2 freq      +639 delay    102',
Should lined 38 & 39 be their own test in accept?

2023-06-27 09:56 UTC, spenced requested changes
A few small comments, looks in good shape.

2023-06-27 09:56 UTC, spenced commented on src/vse_sync_pp/parse.py
> +
```suggestion
```

2023-06-27 09:56 UTC, spenced commented on tests/vse_sync_pp/analyzers/test_phc2sys.py
> +"""Test cases for vse_sync_pp.analyzers.ts2phc"""
```suggestion
"""Test cases for vse_sync_pp.analyzers.phc2sys"""
```

2023-06-27 09:56 UTC, spenced commented on tests/vse_sync_pp/analyzers/test_phc2sys.py
> +)
```suggestion
from vse_sync_pp.analyzers.phc2sys import TimeErrorAnalyzer
```

2023-06-27 09:56 UTC, spenced commented on tests/vse_sync_pp/analyzers/test_phc2sys.py
> +)
Alternatively, add a comma after `TimeErrorAnalyzer` if you're listing symbols out

2023-06-27 09:56 UTC, spenced commented on tests/vse_sync_pp/analyzers/test_phc2sys.py
> +    """Test cases for vse_sync_pp.analyzers.ts2phc.TimeErrorAnalyzer"""
```suggestion
    """Test cases for vse_sync_pp.analyzers.phc2sys.TimeErrorAnalyzer"""
```

2023-06-27 09:56 UTC, spenced commented on tests/vse_sync_pp/parsers/test_phc2sys.py
> +        (   'phc2sys[681011.839]: [ptp4l.0.config] '
Also need a case where ` [ptp4l.0.config]` (including leading single space) is absent

2023-06-27 09:56 UTC, spenced commented on tests/vse_sync_pp/parsers/test_phc2sys.py
> +            'phc2sys[847916.839]: '
Acknowledging that config file item is absent here (I still propose it needs to be in `accept`).

2023-06-27 10:00 UTC, nocturnalastro commented on tests/vse_sync_pp/parsers/test_phc2sys.py
> +            'CLOCK_REALTIME phc offset          4 s2 freq      +639 delay    102',
Already covered in spenced's comment

2023-06-27 11:54 UTC, spenced commented on src/vse_sync_pp/parsers/phc2sys.py
> +    """Parse time error from a p log message"""
```suggestion
    """Parse time error from a phc2sys log message"""
```

2023-06-27 11:54 UTC, spenced approved these changes

2023-06-27 11:56 UTC, nocturnalastro approved these changes

2023-06-27 13:33 UTC, merged